services:
  wordpress:
    image: wordpress:latest
    user: "33"
    volumes:
      - ./:/var/www/html
      - ../files/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_HOST: wp_db
      WORDPRESS_DB_NAME: ferre152_bulcano
      WORDPRESS_DB_USER: ferre152_bulcano
      WORDPRESS_DB_PASSWORD: xf809+W0gl_C
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-0}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_MEMORY_LIMIT', '256M');
        define('DISALLOW_FILE_EDIT', true);
    depends_on:
      wp_db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - default

  wp_db:
    image: mysql:8.4
    restart: unless-stopped
    volumes:
      - wp_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: xf809+W0gl_C # OK - Contraseña del usuario root
      MYSQL_DATABASE: ferre152_bulcano # OK - Crea la DB

      # DEBES agregar la definición del usuario y contraseña
      MYSQL_USER: ferre152_bulcano # <--- AGREGAR ESTA LÍNEA
      MYSQL_PASSWORD: xf809+W0gl_C # <--- AGREGAR ESTA LÍNEA
    healthcheck:
      test: [ "CMD-SHELL", "exit | mysql -h localhost -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    labels:
      # Etiqueta crucial para que Traefik se conecte al puerto interno 80
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
    environment:
      PMA_HOST: wp_db
      # CORRECCIÓN: Usa MYSQL_ROOT_PASSWORD para que inicie sesión automáticamente con root
      MYSQL_ROOT_PASSWORD: xf809+W0gl_C
    depends_on:
      wp_db:
        condition: service_healthy
    networks:
      - default

# ---

volumes:
  wp_data:
  wp_uploads:
    # Añadido para consistencia si lo usaste en el servicio wordpress

    # ---

networks:
  default:
    external: true
